name: sample_env_functional_genomics
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - blas=1.0=mkl
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates
  - certifi
  - charset-normalizer=3.3.2
  - contourpy=1.0.5
  - cycler=0.11.0
  - fonttools=4.51.0
  - freetype=2.12.1
  - icu=73.1
  - idna=3.7
  - importlib_resources=6.4.0
  - intel-openmp
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libdeflate
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openssl
  - packaging=24.1
  - pandas=2.0.3
  - patsy=0.5.6
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - requests=2.32.3
  - scipy=1.10.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - statsmodels=0.14.0
  - tbb=2021.8.0
  - tomli=2.0.1
  - tornado=6.4.1
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6